# Generated by Django 4.0.4 on 2022-05-31 16:58

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='media/blogs/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('categorys', models.CharField(choices=[('Birthday', 'Birthday'), ('anniversary', 'anniversary'), ('proposal', 'proposal'), ('party', 'party')], max_length=255)),
                ('body', ckeditor.fields.RichTextField(default='')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
