# Generated by Django 4.0.4 on 2022-05-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='categorys',
            field=models.CharField(choices=[('birthday', 'birthday'), ('anniversary', 'anniversary'), ('proposal', 'proposal'), ('party', 'party')], max_length=255),
        ),
    ]
