# Generated by Django 4.0.4 on 2022-05-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imgs',
            field=models.ImageField(upload_to='media/%Y/%m/'),
        ),
    ]
