# Generated by Django 4.0.4 on 2022-06-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_imgs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-id',)},
        ),
    ]
